@startuml

partition "日々の蓄積" {
    (*) --> === S1 ===
    partition "Prototypeの登録[Prototyper]" {
    === S1 === --> "Protopedia に制作物レポートを追加"
    }
    --> === S2 ===

    partition "Prototyperの分析[Owner & Prototyper on BITool]" {
    === S1 === --> "Material, Role, Tag, Member の分布を調べる"
    --> "Member とTag の相関を調べる"
    --> "Member とMaterial の相関を調べる"
    --> "Material とTag の相関を調べる"
    --> "自分と類似したPrototyper を検索する"
    }
    --> === S2 ===

    partition "データの抽出[ProtopediaHackServer]" #LightSkyBlue {
    === S1 === --> "キーワード検索の結果を取得する"
    --> "開発物のサイトの中身を取得する"
    --> "開発物のサイトの中身を解析する"
    --> "Title, Tag, Role, Material, Member をDB に登録する"
    --> "Materialと Member の共起情報からMember をベクトル化する"
    --> "制作者同士のコサイン類似度を算出してDB に登録する"
    }
    --> === S2 ===
}

partition "ハッカソンの準備" {
    partition "参加者の作業" {
        --> "Conpass で自身のProtopedia ID を入力する"
        --> "Conpass で参加登録する"
    }
    partition "運営側の作業" {
        --> "Conpass ID とProtopedia とをProtopediaHackServer に登録する"
        
    }
}

partition "ハッカソン当日の流れ" {
    --> "開会の挨拶"
    --> "提供素材の説明"
    --> "仮に人をグループ分けして挨拶・会話してもらう"
    note left #LightPink
    レッドハッカソンではこれを手動でやっていた・・・
    end note
    --> "アイデア画像を作成して登録する（写真でもＯＫ）"
    note left #LightPink
    汎用フォーマットのデータにしたいので画像が無難か？
    マジックで書きなぐって写真を撮るとか、手抜きしやすい。
    end note
    --> "必要なMaterials (開発環境・ライブラリ・ＡＰＩなど)をアイデアに関連付ける"
    note left
    表記ゆれを防ぐのと、入力を楽にするために、
    入力予測があると嬉しい
    end note
    --> "自分のアイデア用のチャットルームを開く"
    note left
    ここの会話でZoom を使うのは恐らく好ましくない。
    Zoom は全体で会話を共有することにだけ使う。
    他の人のアイデアにコメントするのと、自分のアイデアにコメントして
    くれた人に返事をするのと、両方を並行して実施してほしいため。
    今までのリアルハッカソンではこの辺が課題になってて、
    アイデアの説明をするか、説明を聞くか、どちらかしかできなかったので、
    一つの進化ポイントになるのではないかと期待。
    end note
    --> "関係しそうな人に自分のチャットルームがアピールされる"
    note left #LightPink
    何らかの通知が届くとか、
    チャットルームへのリンクが強調表示されるとか。
    LINE で通知してみるとか
    end note
    --> === S3 ===

    === S3 === --> "チャットルームを選択してコメントする"
    --> "気に入ったらお気に入りボタンを押す"
    note right
    押せるお気に入りボタンの数は制限される
    自分のチャットルームにお気に入りは
    押せないようにもできる
    end note
    --> === S4 ===


    === S3 === --> "自分のチャットルームに来たコメントに応答する"
    --> === S4 ===

    === S3 === --> "運営から適宜Zoom でアナウンスする"
    note right
    Zoom の回線は全体での運営用に占有する
    end note
    --> "各チャットルームのお気に入りボタンの押下回数一覧を確認する"
    --> "各チャットルームのMaterial の充足状況を確認する"
    note right
    end note
    --> === S4 ===

    --> "一定時間経過する"

    --> "個別にメンバーを呼び出す（適宜）"
    note right
    これはLINE API を使ってみてもよい1
    end note

    --> "アイデア選択のアナウンス"

    --> "各自アイデアを発表する"
    note right #LightPink
    制限時間が分かりやすくなるようにする
    end note

    --> "各参加者がいずれかのチャットルームに対して参加ボタンを押す"

    --> "各チャットルームへの参加人数を確認する"
    note left #LightPink
    ハッカソンの形態に応じて最低チームメンバー数を
    設定したり、ボッチソンありで進めたりする。
    自分のアイデアと他の人のアイデア両方に投票した場合、
    自分のアイデアを優先させるので、他の人のアイデアに
    カウントさせないとか、地味な工夫も必要。
    end note

    --> "参加ボタン・参加取り消しボタンを押しながら人数を調節していく"
    note left #LightPink
    パワポを共有してアイコンを張り付けてもよいが、
    ２重投票の心配があるのと、集計が面倒
    end note

    --> "チームが確定したら開発を開始する"
}

@enduml
