version: "3.0"

services:
  nodered_trial:
    image: nodered/node-red:latest
    environment:
      - FLOWS=trial_flows.json
    restart: always
    ports:
      - "${NODE_RED_PORT}:1880"
    volumes:
#      - nodered_volume:/data
      - ./mount/nodered:/data

  # MySQL
  db:
    image: mysql:5.7
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./mount/db/data:/var/lib/mysql
    - ./mount/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./mount/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306

  # phpMyAdmin
  phpmyadmin:
    container_name: test_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=mysql_host
    - PMA_USER=root
    - PMA_PASSWORD=root
    ports:
    - 8080:80  

#volumes:
#  nodered_volume:
#    driver_opts:
#      type: none
#      device: /home/kusanagi/nodered.mysql.superset/nodered
#      o: bind

#networks:
#  node-red-net:


