version: "3.0"

services:
  nodered:
    image: nodered/node-red:latest
    container_name: ${CONTAINER_BASE_NAME}_nodered_host
    environment:
      - FLOWS=${NODE_RED_FLOW}.json
      - NODE_RED_CREDENTIAL_SECRET=${NODE_RED_CREDENTIAL_SECRET}
    restart: always
    ports:
      - "${NODE_RED_PORT}:1880"
    volumes:
      - ./mount/nodered:/data

  # MySQL
  db:
    image: mysql:5.7
    container_name: ${CONTAINER_BASE_NAME}_mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mount/db/data:/var/lib/mysql
      - ./mount/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mount/db/sql:/docker-entrypoint-initdb.d
    ports:
      - ${MYSQL_PORT}:3306

  # phpMyAdmin
  phpmyadmin:
    container_name: ${CONTAINER_BASE_NAME}_phpmyadmin
    depends_on: 
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=${CONTAINER_BASE_NAME}_mysql_host
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    ports:
      - ${PMA_PORT}:80  

  nginx:
    container_name: ${CONTAINER_BASE_NAME}_nginx
    image: nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./mount/nginx/public:/usr/share/nginx/html

  superset:
    container_name: ${CONTAINER_BASE_NAME}_superset
    build: ./dockerfile/superset
    ports:
      - 8088:8088
    volumes:
      - ./mount/superset:/var/lib/superset

